### ISSUE TITLE
Fix typo on royaltyRecpient

### ISSUE THREAD

**Issue by george-e-d-g-e** [olta-art/editions-subgraph#32]
should be royaltyRecipient

**Comment by thewhodidthis** [comment]
Making note here, we should then tweak the corresponding editions app GQL query [github.com/olta-art/editions-app/blob/main/query.js#L62](https://github.com/olta-art/editions-app/blob/main/query.js#L62)

**Comment by george-e-d-g-e** [comment]
#37, olta-art/editions-app#159

**Comment by george-e-d-g-e** [comment]
Will close when subgraph deployments have been updated
